-- 1️⃣ Show total counts in all key tables (fix: use aliases or column names without single quotes)
SELECT 'EMPLOYEE' AS TableName, COUNT(*) AS TotalRows FROM dbo.EMPLOYEE
UNION ALL
SELECT 'ACCESSCATALYST', COUNT(*) FROM dbo.ACCESSCATALYST
UNION ALL
SELECT 'ORGANIZATION', COUNT(*) FROM dbo.ORGANIZATION
UNION ALL
SELECT 'USERPROFILE', COUNT(*) FROM dbo.USERPROFILE
UNION ALL
SELECT 'USERPROFILE_FIELD', COUNT(*) FROM dbo.USERPROFILE_FIELD
UNION ALL
SELECT 'USERPROFILE_HISTORY', COUNT(*) FROM dbo.USERPROFILE_HISTORY
UNION ALL
SELECT 'SCALETYPE', COUNT(*) FROM dbo.SCALETYPE
UNION ALL
SELECT 'SCALE', COUNT(*) FROM dbo.SCALE;

-- 2️⃣ Check EMPLOYEE → ORGANIZATION validity
SELECT TOP 10 e.EMPLOYEE, e.ORGANIZATION
FROM dbo.EMPLOYEE e
LEFT JOIN dbo.ORGANIZATION o ON e.ORGANIZATION = o.ORGANIZATION
WHERE o.ORGANIZATION IS NULL;

-- 3️⃣ Check ACCESSCATALYST → EMPLOYEE validity
SELECT TOP 10 a.ACCESSCATALYST, a.EMPLOYEE
FROM dbo.ACCESSCATALYST a
LEFT JOIN dbo.EMPLOYEE e ON a.EMPLOYEE = e.EMPLOYEE
WHERE e.EMPLOYEE IS NULL;

-- 4️⃣ Check USERPROFILE → ACCESSCATALYST validity
SELECT TOP 10 u.USERFIELD, u.ACCESSCATALYST
FROM dbo.USERPROFILE u
LEFT JOIN dbo.ACCESSCATALYST a ON u.ACCESSCATALYST = a.ACCESSCATALYST
WHERE a.ACCESSCATALYST IS NULL;

-- 5️⃣ Check USERPROFILE → USERPROFILE_FIELD validity
SELECT TOP 10 u.USERFIELD
FROM dbo.USERPROFILE u
LEFT JOIN dbo.USERPROFILE_FIELD f ON u.USERFIELD = f.USERPROFILE_FIELD_ID
WHERE f.USERPROFILE_FIELD_ID IS NULL;

-- 6️⃣ Check USERPROFILE_HISTORY → USERPROFILE + ACCESSCATALYST validity
SELECT TOP 10 h.USERPROFILE_HISTORY_ID, h.USERPROFILE_ID, h.ACCESSCATALYST
FROM dbo.USERPROFILE_HISTORY h
LEFT JOIN dbo.USERPROFILE u ON h.USERPROFILE_ID = u.USERFIELD
LEFT JOIN dbo.ACCESSCATALYST a ON h.ACCESSCATALYST = a.ACCESSCATALYST
WHERE u.USERFIELD IS NULL OR a.ACCESSCATALYST IS NULL;

-- 7️⃣ Show number of changes per person (proves USERPROFILE_HISTORY working)
SELECT 
    e.GENDER,
    e.GIVENNAME,
    e.SURNAME,
    COUNT(*) AS NumberOfChanges
FROM dbo.USERPROFILE_HISTORY h
INNER JOIN dbo.ACCESSCATALYST a ON h.ACCESSCATALYST = a.ACCESSCATALYST
INNER JOIN dbo.EMPLOYEE e ON a.EMPLOYEE = e.EMPLOYEE
GROUP BY e.GENDER, e.GIVENNAME, e.SURNAME
ORDER BY NumberOfChanges DESC;

-- 8️⃣ Recent profile changes in the last 30 days
SELECT 
    e.GIVENNAME,
    e.SURNAME,
    h.OLD_VALUE,
    h.NEW_VALUE,
    h.MODIFIED,
    h.REASON
FROM dbo.USERPROFILE_HISTORY h
INNER JOIN dbo.ACCESSCATALYST a ON h.ACCESSCATALYST = a.ACCESSCATALYST
INNER JOIN dbo.EMPLOYEE e ON a.EMPLOYEE = e.EMPLOYEE
WHERE h.MODIFIED >= DATEADD(DAY, -30, GETDATE())
ORDER BY h.MODIFIED DESC;
